### ISSUE TITLE
function nf

### ISSUE THREAD

**Issue by mimorisuzuko** [patchgi/tw4Downloader#2]
拝啓　パッチギ様

春爛漫の好季節を迎え，毎日お元気でご活躍のことと存じます．失礼ながらソースコードの方を拝見させて頂きました．少しではありますが，お力になれるかと思い，このようなIssueを書かせていただいております．さて，本題ですが以下の関数についてです．

``` javascript
//0埋め関数
function nf(_num) {
    if (_num < 10) {
        return "000" + _num;
    }
    else if (_num < 100) {
        return "00" + _num;
    }
    else if (_num < 1000) {
        return "0" + _num;
    }
    else {
        return _num;
    }
}
```

以下のように記述することで，非常に些細な修正でありますが，より短く書くことができます．パッチギ様の書き方もあると思います．ですので，是非パッチギ様の意見についてもご返信いただければと考えております．

``` javascript
const nf = (n) => {
    return ('000'+n).slice(-4);
};
```

うららかな好季節，心穏やかにお過ごしください．

敬具

**Comment by patchgi** [comment]
いいんじゃない？採用
